answer:
    path:     /
    defaults: { _controller: "VPVotingBundle:Answer:index" }

answer_show:
    path:     /{id}/show
    defaults: { _controller: "VPVotingBundle:Answer:show" }

answer_new:
    path:     /new
    defaults: { _controller: "VPVotingBundle:Answer:new" }

answer_create:
    path:     /create
    defaults: { _controller: "VPVotingBundle:Answer:create" }
    methods:  POST

answer_edit:
    path:     /{id}/edit
    defaults: { _controller: "VPVotingBundle:Answer:edit" }

answer_update:
    path:     /{id}/update
    defaults: { _controller: "VPVotingBundle:Answer:update" }
    methods:  [POST, PUT]

answer_delete:
    path:     /{id}/delete
    defaults: { _controller: "VPVotingBundle:Answer:delete" }
    methods:  [POST, DELETE]
