poll:
    path:     /
    defaults: { _controller: "VPVotingBundle:Poll:index" }

poll_show:
    path:     /{id}/show
    defaults: { _controller: "VPVotingBundle:Poll:show" }

poll_new:
    path:     /new
    defaults: { _controller: "VPVotingBundle:Poll:new" }

poll_create:
    path:     /create
    defaults: { _controller: "VPVotingBundle:Poll:create" }
    methods:  POST

poll_delete:
    path:     /{id}/delete
    defaults: { _controller: "VPVotingBundle:Poll:delete" }
    methods:  [POST, DELETE]

poll_showResults:
    path: /{id}/results
    defaults: { _controller: "VPVotingBundle:Poll:showResults"}
