result:
    path:     /
    defaults: { _controller: "VPVotingBundle:Result:index" }

result_show:
    path:     /{id}/show
    defaults: { _controller: "VPVotingBundle:Result:show" }

result_new:
    path:     /new
    defaults: { _controller: "VPVotingBundle:Result:new" }

result_create:
    path:     /create
    defaults: { _controller: "VPVotingBundle:Result:create" }
    methods:  POST

result_edit:
    path:     /{id}/edit
    defaults: { _controller: "VPVotingBundle:Result:edit" }

result_update:
    path:     /{id}/update
    defaults: { _controller: "VPVotingBundle:Result:update" }
    methods:  [POST, PUT]

result_delete:
    path:     /{id}/delete
    defaults: { _controller: "VPVotingBundle:Result:delete" }
    methods:  [POST, DELETE]