vote:
    path:     /
    defaults: { _controller: "VPVotingBundle:Vote:index" }

vote_show:
    path:     /{id}/show
    defaults: { _controller: "VPVotingBundle:Vote:show" }

vote_new:
    path:     /new
    defaults: { _controller: "VPVotingBundle:Vote:new" }

vote_create:
    path:     /create/{id}/
    defaults: { _controller: "VPVotingBundle:Vote:create", id:1 }
    methods:  [ GET, POST]