vp_voting_vote:
    resource: "@VPVotingBundle/Resources/config/routing/vote.yml"
    prefix:   /vote

vp_voting_poll:
    resource: "@VPVotingBundle/Resources/config/routing/poll.yml"
    prefix:   /poll

